apiVersion: apps/v1
kind: Deployment
metadata:
  name: kenobi-deployment
  labels:
    app: kenobi
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kenobi
  template:
    metadata:
      labels:
        app: kenobi
    spec:
      containers:
      - name: kenobi
        image: lmacuga/kenobi:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        resources:
          limits:
            memory: "800Mi"
          requests:
            memory: "400Mi"