apiVersion: apps/v1
kind: Deployment
metadata:
  name: grievous-deployment
  labels:
    app: grievous
spec:
  replicas: 2
  selector:
    matchLabels:
      app: grievous
  template:
    metadata:
      labels:
        app: grievous
    spec:
      containers:
      - name: grievous
        image: lmacuga/grievous:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        resources:
          limits:
            memory: "800Mi"
          requests:
            memory: "400Mi"